export const defaultTheme = {
  colors: {
    blue: '#3294F8',
    'base-title': '#E7EDF4',
    'base-subtitle': '#C4D4E3',
    'base-text': '#AFC2D4',
    'base-span': '#7B96B2',
    'base-label': '#3A536B',
    'base-border': '#1C2F41',
    'base-post': '#112131',
    'base-profile': '#0B1B2B',
    'base-background': '#071422',
    'base-input': '#040F1A',
    'base-white': '#FFFFFF',
    'base-card': '#F3F2F2',
    'base-button': '#E6E5E5',
    'base-hover': '#D7D5D5',
    'base-error': '#f84747',
    'brand-purple-dark': '#4B2995',
    'brand-purple': '#8047F8',
    'brand-purple-light': '#EBE5F9',
    'brand-yellow-dark': '#C47F17',
    'brand-yellow': '#DBAC2C',
    'brand-yellow-light': '#F1E9C9',
  },
  textSizes: {
    'title-title-xl': '3rem',
    'title-title-l': '2rem',
    'title-title-m': '1.5rem',
    'title-title-s': '1.2rem',
    'title-title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-bold-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: "'Nunito'",
  },
}
